### PR TITLE
Add feature image to the top of blog posts

### PR DESCRIPTION
**Pull request by jam-pot**
Want a pretty picture at the top of your post?

1. Add the following to the flags section of your post:
```
image: <name of image file>
```
2. Add the image to images/feature_images/

Don't want a pretty picture? Well... that's fine too.

### CODE REVIEW

**Comment by Rucknar** [comment]
How much has this been tested? Not far off completing a new blog and i'm tempted to make use of it :)

**Comment by jam-pot** [comment]
Tested in latest version of IE, Chrome, Firefox and Edge. Haven't tried out Safari.

**Comment by jam-pot** [comment]
Works in Safari.

**Comment by Rucknar** [comment]
Just tested in Chrome, doesn't break anything for the existing blogs. Do we have any guidelines for this repo around approving/merging @a-h ?

**Comment by a-h** [comment]
No guidelines yet. Talk it through in Slack?

**Pull request merged**
